### ISSUE TITLE
Build fail after update to Xcode 14.0

### ISSUE THREAD

**Issue by trashersmasher** [webim/webim-client-sdk-cordova-plugin#12]
After updating to Xcode 14.0 build fails with error:
..../Plugins/ru.webim.sdk/SQLiteHistoryStorage.swift:252:9: error build: The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions

**Comment by webim** [comment]
Issue fixed in version 1.9.1.

**Comment by webim** [comment]
Close issue.
